# Generated by Django 5.2.7 on 2025-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_material',
            name='total_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
