# Generated by Django 5.2.7 on 2025-11-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_material_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='worker_no',
            field=models.CharField(blank=True, default='--', max_length=50, null=True),
        ),
    ]
