# Generated by Django 5.2.7 on 2025-11-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_details_worker_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='worker_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
