# Generated by Django 5.2.7 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_details_worker_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='programer_details',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
