# Generated by Django 5.2.7 on 2025-11-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_programer_details_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='acc_details',
            name='created_by_acc',
        ),
        migrations.RemoveField(
            model_name='qa_details',
            name='created_by_acc',
        ),
        migrations.RemoveField(
            model_name='inward',
            name='user',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user'),
        ),
        migrations.RemoveField(
            model_name='programer',
            name='user',
        ),
        migrations.AlterField(
            model_name='programer_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user'),
        ),
        migrations.RemoveField(
            model_name='qa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acc_details',
            name='created_by_qa',
        ),
        migrations.RemoveField(
            model_name='qa_details',
            name='created_by_qa',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='all_user',
            name='role_type',
        ),
        migrations.AddField(
            model_name='acc_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user'),
        ),
        migrations.AddField(
            model_name='all_user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qa_details',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.all_user'),
        ),
        migrations.AddField(
            model_name='all_user',
            name='role',
            field=models.ManyToManyField(blank=True, to='api.role'),
        ),
        migrations.DeleteModel(
            name='accountent',
        ),
        migrations.DeleteModel(
            name='inward',
        ),
        migrations.DeleteModel(
            name='Programer',
        ),
        migrations.DeleteModel(
            name='QA',
        ),
    ]
