# Generated by Django 5.2.7 on 2025-12-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_remove_acc_details_created_by_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_material',
            name='bay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
