# Generated by Django 5.2.7 on 2025-12-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_material_bay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_details',
            name='operator_name',
        ),
    ]
